name: geoffrey
version: 0.2.4
description: >-
  Geoofray is a modern http framework inspired by JavaScript modules and react-/vueJS hooks. 
  It's focus is low level abstraction (depend less on 3rd party packages), simplicity, 
  modular approach, safety and of caurse performance.
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  dio: 3.0.10
  meta: ^1.2.2
  mime_type: ^0.3.2
  test: 1.15.3
