name: Dart CI

on:
  push:
    branches:
      - development
      - feature/*
      - test/*
      - hotfix/*

jobs:
  test:
    name: Unit Tests 
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Running tests
        run: pub run test
